# Generated by Django 4.0.1 on 2022-03-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
