# Generated by Django 3.2.4 on 2021-07-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_plant_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='time',
            new_name='date',
        ),
        migrations.AddField(
            model_name='plant',
            name='datetime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
