# Generated by Django 3.2.4 on 2021-07-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_plant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
