# Generated by Django 3.2.4 on 2021-07-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_action_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='done',
            field=models.CharField(default='Исполняется', max_length=11),
        ),
    ]
