# Generated by Django 3.2.4 on 2021-07-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_plant_numb'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
